baseURL = "https://luke-projects.xyz"
title = "Luke Lipscombe's Site ğŸˆ"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"

[params]
  description = "lukedev820's personal website and portfolio"
  copyright = "Copyright Â© 2022 Luke Lipscombe"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/lukedev820"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "contact"
    url = "mailto:raidernight920@gmail.com"
    weight = 11

[permalinks]
  posts = "/:title/"
[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
